openapi: 3.1.0
info:
  version: "1.0.0"
  title: "Contacts App"
  description: "App documentation for managing contacts"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
servers:
  - url: "http://localhost:3000"
  - url: "https://nodejs-hw-mongodb-tdv4.onrender.com"
tags:
  - name: "Contacts"
    description: "Endpoints related to managing contacts"
  - name: "Auth"
    description: "Endpoints for authentication"
paths:
  /contacts:
    get:
      $ref: "../swagger/paths/contacts/get.yaml"
    post:
      $ref: "../swagger/paths/contacts/post.yaml"
  /contacts/{contactId}:
    parameters:
      - in: path
        name: contactId
        required: true
        schema:
          type: string
          default: "507f1f77bcf86cd799439011"   
        description: "Unique identifier of the contact"
    get:
      $ref: "../swagger/paths/contacts/id/get.yaml"
    patch:
      $ref: "../swagger/paths/contacts/id/patch.yaml"
    delete:
      $ref: "../swagger/paths/contacts/id/delete.yaml"
  /auth/login:
    post:
      $ref: "../swagger/paths/auth/login.yaml"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    contact:
      $ref: "../swagger/components/schemas/contact.yaml"
  responses:
    401:
      $ref: "../swagger/components/responses/401.yaml"
